---
version: '2.3'

volumes:
  data-postgres: {}
  data-opennms-share: {}

networks:
  net.stuttgart:
      driver: bridge
      ipam:
        config:
          - subnet: 172.30.0.0/16
  net.fulda:
      driver: bridge
      ipam:
        config:
          - subnet: 172.31.0.0/16
services:
  database:
    image: postgres:12
    container_name: demo-database
    env_file:
      - .postgres.env
    environment:
      - TZ=Europe/Berlin
    ports:
      - "5432:5432"
    volumes:
      - data-postgres:/var/lib/postgresql/data
    networks:
      net.stuttgart:
        ipv4_address: 172.30.0.10

  opennms:
    image: opennms/horizon:26.2.2
    container_name: demo-horizon-core-web
    cap_add:
      - NET_ADMIN
    networks:
      net.stuttgart:
        ipv4_address: 172.30.0.11
    env_file:
      - .opennms.env
      - .postgres.env
    environment:
      - TZ=Europe/Berlin
    depends_on:
      - database
    volumes:
      - ./etc:/opt/opennms/etc
      - data-opennms-share:/data-opennms-share
      - ./etc-overlay:/opt/opennms-etc-overlay
    command: ["-s"]
    ports:
      - "8980:8980"
      - "8101:8101"
      - "61616:61616"
      - "162:162/udp"

  grafana:
    image: opennms/helm:latest
    container_name: demo-grafana
    networks:
      net.stuttgart:
        ipv4_address: 172.30.0.9
    environment:
      - TZ=Europe/Berlin
    env_file:
      - .grafana.env
    ports:
      - "3000:3000"

  minion-fulda-01:
    image: opennms/minion:26.2.1
    container_name: demo-fd-minion-01
    networks:
      net.stuttgart:
        ipv4_address: 172.30.0.12
      net.fulda:
        ipv4_address: 172.31.0.12
    env_file:
      - .minion-fulda-01.env
    command: ["-f"]
    ports:
      - "8201:8201"
      - "18980"
      - "162/udp"
      - "514/udp"

  srv-stuttgart-01:
    image: indigo/docker-netsnmp
    container_name: demo-str-srv-01
    networks:
      net.stuttgart:
        ipv4_address: 172.30.0.32
    environment:
      - TZ=Europe/Berlin
    ports:
      - "161/udp"

  srv-stuttgart-02:
    image: indigo/docker-netsnmp
    container_name: demo-str-srv-02
    networks:
      net.stuttgart:
        ipv4_address: 172.30.0.33
    environment:
      - TZ=Europe/Berlin
    ports:
      - "161/udp"

  web-stuttgart-01:
    image: httpd
    container_name: demo-str-web-01
    networks:
      net.stuttgart:
        ipv4_address: 172.30.0.34
    environment:
      - TZ=Europe/Berlin
    ports:
      - "80"

  srv-fulda-01:
    image: indigo/docker-netsnmp
    container_name: demo-fd-srv-01
    networks:
      net.fulda:
        ipv4_address: 172.31.0.32
    environment:
      - TZ=Europe/Berlin
    ports:
      - "161/udp"

  srv-fulda-02:
    image: indigo/docker-netsnmp
    container_name: demo-fd-srv-02
    networks:
      net.fulda:
        ipv4_address: 172.31.0.33
    environment:
      - TZ=Europe/Berlin
    ports:
      - "161/udp"

  web-fulda-01:
    image: httpd
    container_name: demo-fd-web-01
    networks:
      net.fulda:
        ipv4_address: 172.31.0.34
    environment:
      - TZ=Europe/Berlin
    ports:
      - "80"
