version: '2'
networks:
  net-stuttgart:
      driver: bridge
      ipam:
        config:
          - subnet: 172.30.0.0/16
  net-fulda:
      driver: bridge
      ipam:
        config:
          - subnet: 172.31.0.0/16
services:
  database_data:
    image: tianon/true
    volumes:
        - /var/lib/postgresql/data
  database:
    image: postgres:9.6.1
    networks:
      net-stuttgart:
        ipv4_address: 172.30.0.10
    env_file:
      - .postgres.env
    ports:
      - "5432:5432"
    depends_on:
      - database_data
    volumes_from:
      - database_data:rw
  opennms_data:
    image: tianon/true
    volumes:
        - /opennms-data
  opennms:
    image: opennms/horizon-core-web:rc-19.0.0
    networks:
      net-stuttgart:
        ipv4_address: 172.30.0.11
    env_file:
      - .opennms.env
      - .postgres.env
    depends_on:
      - database
      - opennms_data
    volumes_from:
      - opennms_data:rw
    volumes:
      - ./opennms-config:/opt/opennms/etc
    command: ["-s"]
    ports:
      - "8980:8980"
      - "18980:18980"
      - "1099:1099"
      - "8101:8101"
      - "61616:61616"
      - "5817:5817"
      - "162:162/udp"
  grafana:
    image: grafana/grafana:4.1.1
    networks:
      net-stuttgart:
        ipv4_address: 172.30.0.9
    volumes:
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .grafana.env
    ports:
      - "3000:3000"
  minion-stuttgart-01:
    image: opennms/minion:rc-19.0.0
    networks:
      net-stuttgart:
        ipv4_address: 172.30.0.12
      net-fulda:
        ipv4_address: 172.31.0.12
    env_file:
      - .minion-stuttgart-01.env
    command: ["-f"]
    ports:
      - "8201:8201"
      - "18980"
      - "162/udp"
      - "514/udp"
  srv-stuttgart-01:
    image: indigo/docker-netsnmp
    networks:
      net-stuttgart:
        ipv4_address: 172.30.0.32
    ports:
      - "161/udp"
  srv-stuttgart-02:
    image: indigo/docker-netsnmp
    networks:
      net-stuttgart:
        ipv4_address: 172.30.0.33
    ports:
      - "161/udp"
  web01-stuttgart-01:
    image: httpd
    networks:
      net-stuttgart:
        ipv4_address: 172.30.0.34
    ports:
      - "80"
  srv-fulda-01:
    image: indigo/docker-netsnmp
    networks:
      net-fulda:
        ipv4_address: 172.31.0.32
    ports:
      - "161/udp"
  srv-fulda-02:
    image: indigo/docker-netsnmp
    networks:
      net-fulda:
        ipv4_address: 172.31.0.33
    ports:
      - "161/udp"
  web01-fulda-01:
    image: httpd
    networks:
      net-fulda:
        ipv4_address: 172.31.0.34
    ports:
      - "80"
