version: '2.1'

volumes:
  postgres.data:
    driver: "local"
  opennms.etc:
    driver: "local"
  opennms.data:
    driver: "local"

networks:
  net.core:
      driver: bridge
      ipam:
        config:
          - subnet: 172.30.0.0/16

services:
  opennms.postgres:
    image: postgres:9.6
    container_name: opennms.postgres
    env_file:
      - .postgres.env
    environment:
      - TZ=Europe/Berlin
    volumes:
      - postgres.data:/var/lib/postgresql/data
    networks:
      net.core:
        ipv4_address: 172.30.0.10

  opennms.activemq:
    image: webcenter/activemq:5.14.3
    container_name: opennms.activemq
    environment:
      - TZ=Europe/Berlin
      - ACTIVEMQ_NAME=opennms.amqp.1
      - ACTIVEMQ_REMOVE_DEFAULT_ACCOUNT=true
      - ACTIVEMQ_ADMIN_LOGIN=admin
      - ACTIVEMQ_WRITE_LOGIN=opennms
      - ACTIVEMQ_WRITE_PASSWORD=opennms123
      - ACTIVEMQ_READ_LOGIN=opennms
      - ACTIVEMQ_READ_PASSWORD=opennms123
      - ACTIVEMQ_MIN_MEMORY=256
      - ACTIVEMQ_MAX_MEMORY=1024
      - ACTIVEMQ_ENABLED_SCHEDULER=true
    networks:
      net.core:
        ipv4_address: 172.30.0.11

  opennms.eventd:
    image: opennms/horizon-core-web:stable-healthcheck
    container_name: opennms.eventd
    mem_limit: 2g
    cap_add:
      - NET_ADMIN
    networks:
      net.core:
        ipv4_address: 172.30.0.12
    env_file:
      - .opennms.env
      - .postgres.env
    environment:
      - TZ=Europe/Berlin
    depends_on:
      opennms.postgres:
        condition: service_started
      opennms.activemq:
        condition: service_started
    volumes:
      - opennms.data:/opennms-data
      - ./logs:/opt/opennms/logs
      - ./etc:/opt/opennms/etc
      - ./config/eventd/service-configuration.xml:/opt/opennms/etc/service-configuration.xml
      - ./config/eventd/eventd-configuration.xml:/opt/opennms/etc/eventd-configuration.xml
      - ./config/webapp/event.rtc.properties:/opt/opennms/etc/opennms.properties.d/event.rtc.properties
      - ./config/generic/opennms.activemq.properties:/opt/opennms/etc/opennms.properties.d/opennms.activemq.properties
      - ./config/generic/event.rtc.proxy.properties:/opt/opennms/etc/opennms.properties.d/event.rtc.proxy.properties
    command: ["-s"]

  opennms.webapp:
    image: opennms/horizon-core-web:stable-healthcheck
    container_name: opennms.webapp
    mem_limit: 2g
    cap_add:
      - NET_ADMIN
    networks:
      net.core:
        ipv4_address: 172.30.0.13
    env_file:
      - .opennms.env
      - .postgres.env
    environment:
      - TZ=Europe/Berlin
    depends_on:
      opennms.postgres:
        condition: service_started
      opennms.eventd:
        condition: service_healthy
    volumes:
      - opennms.data:/opennms-data
      - ./etc:/opt/opennms/etc
      - ./config/webapp/service-configuration.xml:/opt/opennms/etc/service-configuration.xml
      - ./config/webapp/event.rtc.properties:/opt/opennms/etc/opennms.properties.d/event.rtc.properties
      - ./config/generic/event.rtc.proxy.properties:/opt/opennms/etc/opennms.properties.d/event.rtc.proxy.properties
      - ./config/generic/opennms.activemq.properties:/opt/opennms/etc/opennms.properties.d/opennms.activemq.properties
    command: ["-f"]
    ports:
      - "8980:8980"
      - "8102:8101"

  opennms.pollerd:
    image: opennms/horizon-core-web:stable-healthcheck
    container_name: opennms.pollerd
    mem_limit: 2g
    cap_add:
      - NET_ADMIN
    networks:
      net.core:
        ipv4_address: 172.30.0.14
    env_file:
      - .opennms.env
      - .postgres.env
    environment:
      - TZ=Europe/Berlin
    depends_on:
      opennms.postgres:
        condition: service_started
      opennms.eventd:
        condition: service_healthy
    volumes:
      - opennms.data:/opennms-data
      - ./etc:/opt/opennms/etc
      - ./config/pollerd/service-configuration.xml:/opt/opennms/etc/service-configuration.xml
      - ./config/generic/event.rtc.proxy.properties:/opt/opennms/etc/opennms.properties.d/event.rtc.proxy.properties
      - ./config/generic/opennms.activemq.properties:/opt/opennms/etc/opennms.properties.d/opennms.activemq.properties
    command: ["-f"]

  opennms.collectd:
    image: opennms/horizon-core-web:stable-healthcheck
    container_name: opennms.collectd
    mem_limit: 2g
    cap_add:
      - NET_ADMIN
    networks:
      net.core:
        ipv4_address: 172.30.0.15
    env_file:
      - .opennms.env
      - .postgres.env
    environment:
      - TZ=Europe/Berlin
    depends_on:
      opennms.postgres:
        condition: service_started
      opennms.eventd:
        condition: service_healthy
    volumes:
      - opennms.data:/opennms-data
      - ./etc:/opt/opennms/etc
      - ./config/collectd/service-configuration.xml:/opt/opennms/etc/service-configuration.xml
      - ./config/generic/event.rtc.proxy.properties:/opt/opennms/etc/opennms.properties.d/event.rtc.proxy.properties
      - ./config/generic/opennms.activemq.properties:/opt/opennms/etc/opennms.properties.d/opennms.activemq.properties
    command: ["-f"]

  opennms.provisiond:
    image: opennms/horizon-core-web:stable-healthcheck
    container_name: opennms.provisiond
    mem_limit: 2g
    cap_add:
      - NET_ADMIN
    networks:
      net.core:
        ipv4_address: 172.30.0.16
    env_file:
      - .opennms.env
      - .postgres.env
    environment:
      - TZ=Europe/Berlin
    depends_on:
      opennms.postgres:
        condition: service_started
      opennms.eventd:
        condition: service_healthy
    volumes:
      - opennms.data:/opennms-data
      - ./etc:/opt/opennms/etc
      - ./config/provisiond/service-configuration.xml:/opt/opennms/etc/service-configuration.xml
      - ./config/generic/event.rtc.proxy.properties:/opt/opennms/etc/opennms.properties.d/event.rtc.proxy.properties
      - ./config/generic/opennms.activemq.properties:/opt/opennms/etc/opennms.properties.d/opennms.activemq.properties
    command: ["-f"]

  opennms.vacuumd:
    image: opennms/horizon-core-web:stable-healthcheck
    container_name: opennms.vacuumd
    mem_limit: 2g
    cap_add:
      - NET_ADMIN
    networks:
      net.core:
        ipv4_address: 172.30.0.17
    env_file:
      - .opennms.env
      - .postgres.env
    environment:
      - TZ=Europe/Berlin
    depends_on:
      opennms.postgres:
        condition: service_started
      opennms.eventd:
        condition: service_healthy
    volumes:
      - opennms.data:/opennms-data
      - ./etc:/opt/opennms/etc
      - ./config/vacuumd/service-configuration.xml:/opt/opennms/etc/service-configuration.xml
      - ./config/generic/event.rtc.proxy.properties:/opt/opennms/etc/opennms.properties.d/event.rtc.proxy.properties
      - ./config/generic/opennms.activemq.properties:/opt/opennms/etc/opennms.properties.d/opennms.activemq.properties
    command: ["-f"]

  opennms.bsmd:
    image: opennms/horizon-core-web:stable-healthcheck
    container_name: opennms.bsmd
    mem_limit: 2g
    cap_add:
      - NET_ADMIN
    networks:
      net.core:
        ipv4_address: 172.30.0.18
    env_file:
      - .opennms.env
      - .postgres.env
    environment:
      - TZ=Europe/Berlin
    depends_on:
      opennms.postgres:
        condition: service_started
      opennms.eventd:
        condition: service_healthy
    volumes:
      - opennms.data:/opennms-data
      - ./etc:/opt/opennms/etc
      - ./config/bsmd/service-configuration.xml:/opt/opennms/etc/service-configuration.xml
      - ./config/generic/event.rtc.proxy.properties:/opt/opennms/etc/opennms.properties.d/event.rtc.proxy.properties
      - ./config/generic/opennms.activemq.properties:/opt/opennms/etc/opennms.properties.d/opennms.activemq.properties
    command: ["-f"]
