version: '2'

volumes:
  postgres-data:
    driver: "local"
  opennms.etc:
    driver: "local"
  opennms.data:
    driver: "local"
  graylog.es.data.01:
    driver: local

networks:
  net.stuttgart:
      driver: bridge
      ipam:
        config:
          - subnet: 172.30.0.0/16
  net.fulda:
      driver: bridge
      ipam:
        config:
          - subnet: 172.31.0.0/16
services:
  database:
    image: postgres:9.6
    container_name: demo-database
    env_file:
      - .postgres.env
    environment:
      - TZ=Europe/Berlin
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      net.stuttgart:
        ipv4_address: 172.30.0.10

  opennms:
    image: opennms/horizon-core-web:stable
    container_name: demo-horizon-core-web
    cap_add:
      - NET_ADMIN
    networks:
      net.stuttgart:
        ipv4_address: 172.30.0.11
    env_file:
      - .opennms.env
      - .postgres.env
    environment:
      - TZ=Europe/Berlin
    depends_on:
      - database
    volumes:
      - opennms.data:/opennms-data
      - ./etc:/opt/opennms/etc
    command: ["-s"]
    ports:
      - "8980:8980"
      - "18980:18980"
      - "1099:1099"
      - "8101:8101"
      - "61616:61616"
      - "5817:5817"
      - "162:162/udp"

  grafana:
    image: opennms/helm:stable
    container_name: demo-grafana
    networks:
      net.stuttgart:
        ipv4_address: 172.30.0.9
    environment:
      - TZ=Europe/Berlin
    env_file:
      - .grafana.env
    ports:
      - "3000:3000"

  minion-fulda-01:
    image: opennms/minion:stable
    container_name: demo-fd-minion-01
    networks:
      net.stuttgart:
        ipv4_address: 172.30.0.12
      net.fulda:
        ipv4_address: 172.31.0.12
    env_file:
      - .minion-fulda-01.env
    command: ["-f"]
    ports:
      - "8201:8201"
      - "18980"
      - "162/udp"
      - "514/udp"

  srv-stuttgart-01:
    image: indigo/docker-netsnmp
    container_name: demo-str-srv-01
    networks:
      net.stuttgart:
        ipv4_address: 172.30.0.32
    environment:
      - TZ=Europe/Berlin
    ports:
      - "161/udp"

  srv-stuttgart-02:
    image: indigo/docker-netsnmp
    container_name: demo-str-srv-02
    networks:
      net.stuttgart:
        ipv4_address: 172.30.0.33
    environment:
      - TZ=Europe/Berlin
    ports:
      - "161/udp"

  web-stuttgart-01:
    image: httpd
    container_name: demo-str-web-01
    networks:
      net.stuttgart:
        ipv4_address: 172.30.0.34
    environment:
      - TZ=Europe/Berlin
    ports:
      - "80"

  srv-fulda-01:
    image: indigo/docker-netsnmp
    container_name: demo-fd-srv-01
    networks:
      net.fulda:
        ipv4_address: 172.31.0.32
    environment:
      - TZ=Europe/Berlin
    ports:
      - "161/udp"

  srv-fulda-02:
    image: indigo/docker-netsnmp
    container_name: demo-fd-srv-02
    networks:
      net.fulda:
        ipv4_address: 172.31.0.33
    environment:
      - TZ=Europe/Berlin
    ports:
      - "161/udp"

  web-fulda-01:
    image: httpd
    container_name: demo-fd-web-01
    networks:
      net.fulda:
        ipv4_address: 172.31.0.34
    environment:
      - TZ=Europe/Berlin
    ports:
      - "80"

  graylog_mongodb:
    image: mongo:3
    container_name: graylog-mongodb
    hostname: mongo
    environment:
      - TZ=Europe/Berlin
    networks:
      net.stuttgart:
        ipv4_address: 172.30.0.13

  graylog_es:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.3
    container_name: elasticsearch1
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - TZ=Europe/Berlin
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 1g
    volumes:
      - graylog.es.data.01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      net.stuttgart:
        ipv4_address: 172.30.0.14

  graylog:
    image: graylog2/server:2.3.1-1
    hostname: graylog
    environment:
      - TZ=Europe/Berlin
      - GRAYLOG_PASSWORD_SECRET=somepasswordpepper
      - GRAYLOG_ROOT_PASSWORD_SHA2=8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918
      - GRAYLOG_WEB_ENDPOINT_URI=http://127.0.0.1:9000/api
    links:
      - graylog_mongodb:mongo
      - graylog_es:elasticsearch
    ports:
      - "9000:9000"
      - "12201:12201/udp"
      - "514:514/udp"
    networks:
      net.stuttgart:
        ipv4_address: 172.30.0.15
