{
 "title": "Top by Prefixes",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "router_name",
    "label": "Filter by Router",
    "query": "select routername from bmp_v_peers group by routername"
   }
  ]
 },
 "panels": [
  {
   "title": "Advertisements & Withdrawals",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  interval_time as time,\n   sum(updates) as updates,sum(withdraws) as withdraws\nFROM bmp_stats_by_peer s\n  JOIN bmp_v_peers p ON (s.peer_hash_id = p.peer_hash_id)\nWHERE $__timeFilter(interval_time)\n  AND routername in ($router_name)\nGROUP BY interval_time\nORDER BY interval_time ASC\n\n"
    }
   ]
  },
  {
   "title": "Advertisements By Router",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "none", "label": "Updates" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n    interval_time as time,\n    updates as updates,\n    p.RouterName as metric\n  FROM bmp_stats_by_peer l\n  JOIN bmp_v_peers p ON (p.peer_hash_id = l.peer_hash_id)\n  WHERE $__timeFilter(interval_time)\n    AND p.routername IN ($router_name)\n  order by interval_time asc\n\n"
    }
   ]
  },
  {
   "title": "Withdraws  By Router",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "none", "label": "Withdraws" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n    interval_time as time,\n    withdraws,\n    p.RouterName as metric\n  FROM bmp_stats_by_peer l\n  JOIN bmp_v_peers p ON (p.peer_hash_id = l.peer_hash_id)\n  WHERE $__timeFilter(interval_time)\n     AND p.routername IN ($router_name)\n  order by interval_time asc\n\n"
    }
   ]
  },
  {
   "title": "Updates by Peer",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "none", "label": "Count of Updates" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n    interval_time as time,\n    updates,\n    p.PeerName as metric\n  FROM bmp_stats_by_peer l\n  JOIN bmp_v_peers p ON (p.peer_hash_id = l.peer_hash_id)\n  WHERE $__timeFilter(interval_time)\n     AND p.routername IN ($router_name)\n  order by interval_time asc\n"
    }
   ]
  },
  {
   "title": "Withdraws  by Peer",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "none", "label": "Count of Updates" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n    interval_time as time,\n    withdraws,\n    p.PeerName as metric\n  FROM bmp_stats_by_peer l\n  JOIN bmp_v_peers p ON (p.peer_hash_id = l.peer_hash_id)\n  WHERE $__timeFilter(interval_time)\n     AND p.routername IN ($router_name)\n  order by interval_time asc\n"
    }
   ]
  },
  {
   "title": "Top Updates by Prefix",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "none", "label": "Updates" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n    max(interval_time) as time,\n    sum(updates) as value,\n    prefix as metric\n  FROM bmp_stats_by_prefix l\n  WHERE $__timeFilter(interval_time)\n      AND peer_hash_id in (SELECT peer_hash_id from bmp_v_peers where routername in ($router_name))\n  GROUP BY prefix\n  order by value desc\nLIMIT 20"
    }
   ]
  },
  {
   "title": "Top Withdraws by Prefix",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "none", "label": "Withdraws" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n    max(interval_time) as time,\n    sum(withdraws) as value,\n    prefix as metric\n  FROM bmp_stats_by_prefix\n  WHERE $__timeFilter(interval_time)\n      AND peer_hash_id in (SELECT peer_hash_id from bmp_v_peers where routername in ($router_name))\n  GROUP BY prefix\n  order by value desc\nLIMIT 20;\n"
    }
   ]
  }
 ]
}