{
 "title": "BGP Sec: RPKI & IRR",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "RPKI Prefixes in Violations",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n      max(timestamp) as time,\n      count(*) as mismatches\n  FROM global_ip_rib\n    WHERE rpki_origin_as > 0 and rpki_origin_as != recv_origin_as\n"
    },
    {
     "rawSql": "SELECT\n      max(timestamp) as time,\n      count(*) as matches\n  FROM global_ip_rib\n    WHERE rpki_origin_as > 0 and rpki_origin_as = recv_origin_as\n\n"
    }
   ]
  },
  {
   "title": "IRR Prefixes in Violations",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 9, "x": 9, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n      max(timestamp) as time,\n      count(*) as mismatches\n  FROM global_ip_rib\n    WHERE irr_origin_as > 0 and irr_origin_as != recv_origin_as\n\n\n"
    },
    {
     "rawSql": "SELECT\n      max(timestamp) as time,\n      count(*) as matches\n  FROM global_ip_rib\n    WHERE irr_origin_as > 0 and irr_origin_as = recv_origin_as\n"
    }
   ]
  },
  {
   "title": "RPKI ROAS",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 0 },
   "format": "locale",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "select count(*) from rpki_validator\n"
    }
   ]
  },
  {
   "title": "IRR Entries",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 4 },
   "format": "locale",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "select count(*) from info_route\n"
    }
   ]
  },
  {
   "title": "Prefixes in Violation of IRR",
   "type": "briangann-datatable-panel",
   "gridPos": { "h": 11, "w": 13, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "select\n     timestamp,\n     prefix as \"Prefix\",\n     recv_origin_as as \"Received Origin\",\n     irr_origin_as as \"Expected Origin\",\n     irr_source as \"IRR Source\"\n  FROM global_ip_rib\n  WHERE $__timeFilter(timestamp)\n      and recv_origin_as > 0 AND irr_origin_as > 0 and recv_origin_as != irr_origin_as\n  limit 1000"
    }
   ]
  },
  {
   "title": "Prefixes in Violation of RPKI",
   "type": "briangann-datatable-panel",
   "gridPos": { "h": 11, "w": 11, "x": 13, "y": 8 },
   "targets": [
    {
     "rawSql": "select\n     timestamp,\n     prefix as \"Prefix\",\n     recv_origin_as as \"Received Origin\",\n     rpki_origin_as as \"Expected Origin\"\n  FROM global_ip_rib\n  WHERE $__timeFilter(timestamp)\n      and recv_origin_as > 0 AND rpki_origin_as > 0 and recv_origin_as != rpki_origin_as\n  limit 1000"
    }
   ]
  }
 ]
}