{
 "title": "Inventory",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Router Status",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 11, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n  floor(extract(epoch from max(r.last_updated))) as time,\n  count(distinct router_hash_id) as value,\n  r.state as metric\nFROM bmp_routers r\n  JOIN bmp_peers p on (r.hash_id = p.router_hash_id)\n  group by r.state\n"
    }
   ]
  },
  {
   "title": "Routers",
   "type": "briangann-datatable-panel",
   "gridPos": { "h": 11, "w": 20, "x": 4, "y": 0 },
   "targets": [
    {
     "rawSql": "select max(r.last_updated) as timestamp,r.name,max(ip_address) as ip_address,max(r.state) as state,\n    count(*) as peers,max(description) as description, CASE WHEN max(r.state) = 'UP' THEN 1 ELSE 0 END as stateBool\n  from bmp_routers r\n  JOIN bmp_peers p on (r.hash_id = p.router_hash_id)\n  GROUP BY r.name;"
    }
   ]
  },
  {
   "title": "Peer Status",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 11 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n  floor(extract(epoch from max(last_updated))) as time,\n  count(*) as value,\n  state as metric\nFROM bmp_peers\n  group by metric"
    }
   ]
  },
  {
   "title": "Peers",
   "type": "briangann-datatable-panel",
   "gridPos": { "h": 14, "w": 20, "x": 4, "y": 11 },
   "targets": [
    {
     "rawSql": " SELECT\n    max(RouterName) as \"RouterName\",\n    max(PeerName) as \"PeerName\",\n    max(PeerIP) as \"PeerIP\",\n    max(PeerASN) as \"PeerASN\",\n    max(peer_state) as \"State\",\n    max(LastModified) as \"LastModified\",\n    max(v4_prefixes) as \"IPv4 Prefixes\",\n    max(v6_prefixes) as \"IPv6 Prefixes\",\n    CASE WHEN max(peer_state) = 'UP' THEN 1 ELSE 0 END as stateBool\nFROM bmp_v_peers p\n  LEFT JOIN bmp_stats_peer_rib s ON (p.peer_hash_id = s.peer_hash_id\n          AND s.interval_time >= now() - interval '20 minutes')\nGROUP BY p.peer_hash_id;\n"
    }
   ]
  }
 ]
}